-- Generated by Nerai Templates (https://nerai.xyz/) for App ID 730
-- Generated: 2026-05-04T23:04:19.686Z
-- Educational template for Steam manifest generation
-- Check README.txt for more information
-- Source: Educational template

-- Main application
addappid(730)

-- Set up depot manifests
setManifestid(228980,"3639655532831812600")
setManifestid(228981,"9444992275818177000")
setManifestid(228982,"3268977147044215000")

-- Add DLC content (educational example)
addappid(2118222,0,"40d11ed25486a2ef6da99114c4f8730f00f6975634999a1d4a53c2047ef78d26")
setManifestid(2118222,"4801911329080220000")

-- Additional configuration for proper Steam recognition
-- These commands help Steam understand the depot structure
-- and ensure proper content downloading

-- End of script
