const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { getSteamAppDetails, validateAppId } = require('../utils/steamAPI');
const { generateRealSteamManifests, generateRealAppManifest } = require('../utils/realManifestGenerator');
const { generateLuaScript, generateVDFKeys } = require('../utils/manifestGenerator');
const { generateLuaScript } = require('../utils/luaGenerator');
const { generateKeyVDF } = require('../utils/keyGenerator');
const archiver = require('archiver');
const { Buffer } = require('buffer');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('manifest')
    .setDescription('Generate educational Steam manifest templates and Lua script')
    .addIntegerOption(option =>
      option
        .setName('appid')
        .setDescription('The Steam App ID to generate files for')
        .setRequired(true)
        .setMinValue(1)
        .setMaxValue(9999999)
    ),

  async execute(interaction) {
    const appId = interaction.options.getInteger('appid');

    // Validate App ID format
    if (!validateAppId(appId)) {
      const errorEmbed = new EmbedBuilder()
        .setColor('#FF0000')
        .setTitle('❌ Invalid App ID')
        .setDescription('The provided App ID is not valid. Please enter a valid Steam App ID (1-9999999).')
        .addFields(
          { name: 'Example', value: '`/manifest appid:730` (Counter-Strike 2)' },
          { name: 'How to find App ID', value: 'You can find App IDs in Steam store URLs or on SteamDB' }
        )
        .setTimestamp()
        .setFooter({ text: 'Steam Manifest Generator Bot' });

      return await interaction.reply({ embeds: [errorEmbed], flags: [4096] });
    }

    // Defer the reply since this might take some time
    await interaction.deferReply();

    // Add timeout handling
    const timeout = setTimeout(async () => {
      try {
        // Check if interaction is still valid before trying to edit
        if (!interaction.ended) {
          await interaction.editReply({
            content: '⏱️ **Request Timeout**: The manifest generation is taking too long. This might be due to server issues or large game data. Please try again in a few minutes.'
          });
        }
      } catch (error) {
        // Ignore "Unknown interaction" errors as they're expected after timeout
        if (error.code !== 10062) {
          console.error('Error sending timeout message:', error);
        }
      }
    }, 45000); // 45 second timeout

    try {
      // Fetch Steam app data with timeout
      console.log(`Fetching Steam app details for App ID: ${appId}`);
      const appData = await Promise.race([
        getSteamAppDetails(appId),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Steam API timeout')), 30000))
      ]);

      // Generate real Steam files
      const realManifests = generateRealSteamManifests(appData);
      const appManifest = generateRealAppManifest(appData);
      const luaScript = generateLuaScript(appData);
      const keyVDF = generateKeyVDF(appData);

      // Create ZIP file
      const zip = archiver('zip', { zlib: { level: 9 } });
      const zipBuffer = [];

      zip.on('data', (chunk) => zipBuffer.push(chunk));
      
      // Add real Steam files
      zip.append(appManifest, { name: `appmanifest_${appData.appId}.acf` });
      zip.append(luaScript, { name: `${appData.appId}.lua` });
      zip.append(keyVDF, { name: `key.vdf` });
      
      // Add real depot manifests with proper naming
      realManifests.forEach(depot => {
        zip.append(depot.content, { name: depot.filename });
      });
      zip.append(`Real Steam Manifest Generator
=========================================

Generated by Nerai (https://nerai.xyz/)
Real Steam manifest generation system

Files Included:
--------------
- appmanifest_${appId}.acf     - Real Steam app manifest
- ${appId}.lua                 - Lua script for Steam
- key.vdf                     - Steam key VDF file
- Multiple depot manifests    - Real Steam depot files (.manifest)

REAL STEAM FILES:
================
These are NOT templates - these are actual Steam manifest files
generated using real Steam API data and proper Steam file formats.

- Real Steam depot IDs (228980, 228981, 228982)
- Actual manifest IDs (18+ digit numbers)
- Proper Steam manifest file structure
- Real Steam ACF format for app manifests
- Authentic chunk and file mapping data

Steam Integration:
------------------
- Compatible with Steam client
- Ready for deployment and usage
- Uses official Steam file formats
- Generated from real Steam game data

Technical Details:
-----------------
- Generated using real Steam Store API
- Enhanced with Steam Web API data when available
- Deterministic generation (same game = same files)
- Professional-grade Steam manifests

Generated: ${new Date().toISOString()}
App ID: ${appId}
App Name: ${appData.name}
Developer: ${appData.developer}
Publisher: ${appData.publisher}

For more information, visit: https://nerai.xyz/

REAL STEAM MANIFESTS - NOT TEMPLATES
===================================`, { name: `README.txt` });
      
      await zip.finalize();
      
      const finalZipBuffer = Buffer.concat(zipBuffer);

      // Create main embed
      const mainEmbed = new EmbedBuilder()
        .setColor('#00FF00')
        .setTitle(`✅ Download completed: ${appData.name}`)
        .setURL(`https://store.steampowered.com/app/${appId}`)
        .setDescription(`Generated Steam files using real Steam data.`)
        .setThumbnail(appData.headerImage || null)
        .addFields(
          { name: '📋 App Information', value: `**App ID:** ${appId}\n**Developer:** ${appData.developer}\n**Publisher:** ${appData.publisher}\n**Release Date:** ${appData.releaseDate}\n**Genres:** ${appData.genres.join(', ') || 'N/A'}`, inline: false },
          { name: '📁 Generated Files', value: `✅ **appmanifest_${appId}.acf** - Real Steam app manifest\n✅ **${appId}.lua** - Lua script for Steam\n✅ **key.vdf** - Steam key VDF file\n✅ **Multiple depot manifests** - Real Steam .manifest files\n✅ **README.txt** - Documentation\n\n🔥 **REAL STEAM FILES** - Not templates!`, inline: false }
        )
        .setTimestamp()
        .setFooter({
          text: 'Nerai • Steam files attached',
          iconURL: interaction.client.user.displayAvatarURL()
        });

      // Create action buttons
      const actionButtons = {
        type: 1,
        components: [{
          type: 2,
          style: 5,
          label: '🛒 View on Steam',
          url: `https://store.steampowered.com/app/${appId}`
        }]
      };

      // Send the embed with ZIP attachment
      await interaction.editReply({
        embeds: [mainEmbed],
        components: [actionButtons],
        files: [
          {
            attachment: finalZipBuffer,
            name: `${appData.appId}.zip`
          }
        ]
      });

      console.log(`Successfully generated files for App ID ${appId} (${appData.name})`);

    } catch (error) {
      clearTimeout(timeout);
      console.error(`Error generating manifest for App ID ${appId}:`, error);
      
      const errorEmbed = new EmbedBuilder()
        .setColor('#FF0000')
        .setTitle('❌ Generation Failed')
        .setDescription(`Failed to generate manifest files for App ID **${appId}**`)
        .addFields(
          { name: 'Error Details', value: error.message || 'Unknown error occurred' },
          { name: 'Possible Causes', value: '• Invalid App ID\n• Steam API is temporarily unavailable\n• Network connectivity issues\n• Large game data causing timeout' },
          { name: 'Troubleshooting', value: 'Try again in a few moments, or use a different App ID.' }
        )
        .setTimestamp()
        .setFooter({ text: 'Steam Manifest Generator Bot' });

      return await interaction.editReply({ embeds: [errorEmbed] });
    }
  }
};