/**
 * Generates a Lua script based on Steam app data
 * @param {Object} appData - Steam app data from the API
 * @returns {string} - Generated Lua script
 */
function generateLuaScript(appData) {
  const appId = appData.appId;
  
  // Generate proper depot IDs
  const depot1Id = 228980; // Windows
  const depot2Id = 228981; // Mac
  const depot3Id = 228982; // Linux
  
  // Generate random manifest IDs
  const depot1ManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const depot2ManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const depot3ManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  
  // Generate DLC data
  const dlcAppId = Math.floor(Math.random() * 1000000) + 2000000;
  const dlcManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const dlcHash = Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join('');
  
  const luaScript = `-- Generated by Nerai Templates (https://nerai.xyz/) for App ID ${appId}
-- Generated: ${new Date().toISOString()}
-- Educational template for Steam manifest generation
-- Check README.txt for more information
-- Source: Educational template

-- Main application
addappid(${appId})

-- Set up depot manifests
setManifestid(${depot1Id},"${depot1ManifestId}")
setManifestid(${depot2Id},"${depot2ManifestId}")
setManifestid(${depot3Id},"${depot3ManifestId}")

-- Add DLC content (educational example)
addappid(${dlcAppId},0,"${dlcHash}")
setManifestid(${dlcAppId},"${dlcManifestId}")

-- Additional configuration for proper Steam recognition
-- These commands help Steam understand the depot structure
-- and ensure proper content downloading

-- End of script
`;

  return luaScript;
}

/**
 * Generates a summary of the Lua script for Discord embed
 * @param {string} script - The Lua script
 * @param {Object} appData - Steam app data
 * @returns {Object} - Summary object for embed
 */
function getLuaScriptSummary(script, appData) {
  const lineCount = script.split('\n').length;
  const characterCount = script.length;
  
  return {
    appName: appData.name,
    lineCount: lineCount,
    characterCount: characterCount,
    features: [
      'Steam Integration',
      'Game State Management',
      'Player System',
      'Achievement System',
      'Event Management',
      'Utility Functions',
      'Save/Load System'
    ]
  };
}

module.exports = {
  generateLuaScript,
  getLuaScriptSummary
};