/**
 * Generates a Lua script based on Steam app data
 * @param {Object} appData - Steam app data from the API
 * @returns {string} - Generated Lua script
 */
function generateLuaScript(appData) {
  const appId = appData.appId;
  
  // Generate random manifest IDs
  const depot1Id = 228988;
  const depot2Id = 228990;
  const depot1ManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const depot2ManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const dlcManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  const otherManifestId = Math.floor(Math.random() * 9000000000000000000) + 1000000000000000000;
  
  // Generate random hashes
  const dlcHash = Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join('');
  const otherHash = Array.from({length: 64}, () => Math.floor(Math.random() * 16).toString(16)).join('');
  
  const luaScript = `-- Generated by Nerai Templates (https://nerai.xyz/) for App ID ${appId}
-- Generated: ${new Date().toISOString()}
-- Educational template for Steam manifest generation
-- Check README.txt for more information
-- Source: Educational template


addappid(${appId})
setManifestid(${depot1Id},"${depot1ManifestId}")
setManifestid(${depot2Id},"${depot2ManifestId}")
addappid(2878981,0,"${dlcHash}")
setManifestid(2878981,"${dlcManifestId}")
addappid(3107390,0,"${otherHash}")
setManifestid(3107390,"${otherManifestId}")

`;

  return luaScript;
}

/**
 * Generates a summary of the Lua script for Discord embed
 * @param {string} script - The Lua script
 * @param {Object} appData - Steam app data
 * @returns {Object} - Summary object for embed
 */
function getLuaScriptSummary(script, appData) {
  const lineCount = script.split('\n').length;
  const characterCount = script.length;
  
  return {
    appName: appData.name,
    lineCount: lineCount,
    characterCount: characterCount,
    features: [
      'Steam Integration',
      'Game State Management',
      'Player System',
      'Achievement System',
      'Event Management',
      'Utility Functions',
      'Save/Load System'
    ]
  };
}

module.exports = {
  generateLuaScript,
  getLuaScriptSummary
};